//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace heshamhrms.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class Authorities
    {
        public Authorities()
        {
            this.Users = new HashSet<Users>();
        }
    
        public int auth_id { get; set; }
        [Display(Name = "«”„ «·’·«ÕÌ…")]
        public string auth_name { get; set; }
    
        public virtual ICollection<Users> Users { get; set; }
    }
}
