//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace heshamhrms.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Courses
    {
    public int Course_id { get; set; }
        public Nullable<int> Course_Course_name_id { get; set; }
        public Nullable<int> Course_Employee_id { get; set; }
         [Display(Name = "„ﬂ«‰ «·œÊ—…")]
        public string Course_location { get; set; }
         [Display(Name = "»œ«Ì… «·œÊ—…")]
         [DataType(DataType.Date)]
        public Nullable<System.DateTime> Course_start_date { get; set; }
         [Display(Name = "‰Â«Ì… «·œÊ—…")]
         [DataType(DataType.Date)]
        public Nullable<System.DateTime> Course_end_date { get; set; }
         [Display(Name = "„œ⁄Ê„ „‰")]
        public string Support_from { get; set; }
         [Display(Name = "«œŒ· »Ê«”ÿ…")]
        public Nullable<int> Edit_by { get; set; }
         [Display(Name = "«· «—ÌŒ")]
         [DataType(DataType.Date)]
        public Nullable<System.DateTime> Date_time { get; set; }
        
        public virtual Courses_name Courses_name { get; set; }
        public virtual Users Users { get; set; }
        public virtual Employees Employees { get; set; }
    }
}
