//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace heshamhrms.Models
{
    using System;
    using System.Collections.Generic;
   using System.ComponentModel.DataAnnotations;
    
    public partial class Departments
    {
        public Departments()
        {
            this.Employees = new HashSet<Employees>();
            this.national_services = new HashSet<national_services>();
            this.Out_jobs = new HashSet<Out_jobs>();
            this.trainings = new HashSet<trainings>();
            this.Transfers = new HashSet<Transfers>();
            this.Transfers1 = new HashSet<Transfers>();
            this.Vacations = new HashSet<Vacations>();
        }
    
    public int Department_id { get; set; }
         [Display(Name = "«”„ «·«œ«—… - «·›—⁄")]
        public string Department_name { get; set; }
         [Display(Name = "«·„œÌ—")]
        public Nullable<int> Manger_id { get; set; }
        public Nullable<int> Department_Location_id { get; set; }
    
        public virtual Locations Locations { get; set; }
        public virtual ICollection<Employees> Employees { get; set; }
        public virtual ICollection<national_services> national_services { get; set; }
        public virtual ICollection<Out_jobs> Out_jobs { get; set; }
        public virtual ICollection<trainings> trainings { get; set; }
        public virtual ICollection<Transfers> Transfers { get; set; }
        public virtual ICollection<Transfers> Transfers1 { get; set; }
        public virtual Employees Employees1 { get; set; }
        public virtual ICollection<Vacations> Vacations { get; set; }
    }
}
