//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace heshamhrms.Models
{
    using System;
    using System.Collections.Generic;
   using System.ComponentModel.DataAnnotations;
    
    public partial class Employees
    {
        public Employees()
        {
            this.alerts = new HashSet<alerts>();
            this.Certificates = new HashSet<Certificates>();
            this.Courses = new HashSet<Courses>();
            this.Leave_permission = new HashSet<Leave_permission>();
            this.Manifestations = new HashSet<Manifestations>();
            this.Out_jobs = new HashSet<Out_jobs>();
            this.Resigns = new HashSet<Resigns>();
            this.sacks = new HashSet<sacks>();
            this.stop_working = new HashSet<stop_working>();
            this.Transfers = new HashSet<Transfers>();
            this.Vacation_Balances = new HashSet<Vacation_Balances>();
            this.Departments1 = new HashSet<Departments>();
            this.Vacations = new HashSet<Vacations>();
        }
    
        public int Employee_id { get; set; }
         [Display(Name = "«”„ «·„ÊŸ›")]
        public string Employee_name { get; set; }
         [Display(Name = "«”„ «·«„")]
        public string Mother_name { get; set; }
         [Display(Name = " «—ÌŒ «·„Ì·«œ")]
         [DataType(DataType.Date)]
         
        public Nullable<System.DateTime> Date_of_birth { get; set; }
        public Nullable<int> Employee_Country_id { get; set; }
         [Display(Name = "«·—ﬁ„ «·Êÿ‰Ì")]
        public string National_no { get; set; }
         [Display(Name = "—ﬁ„ «·Â« ›")]
        public string Phone_no { get; set; }
        public Nullable<int> Employee_Religion_id { get; set; }
        public Nullable<int> Employee_Marital_Status_id { get; set; }
        public Nullable<int> Employee_Qualification_id { get; set; }
         [Display(Name = "«·Ã«„⁄…")]
        public string Employee_Qualification_university { get; set; }
         [Display(Name = " «—ÌŒ «·‘Â«œ…")]
         [DataType(DataType.Date)]
        public Nullable<System.DateTime> Employee_Qualification_date { get; set; }
        public Nullable<int> Employee_high_Qualification_id { get; set; }
         [Display(Name = "«·Ã‰”")]
        public string Employee_high_Qualification_university { get; set; }
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> Employee_high_Qualification_date { get; set; }
         [Display(Name = "«·⁄‰Ê«‰")]
        public string Address { get; set; }
        [DataType(DataType.Date)]
        [Display(Name = " «—ÌŒ «· ⁄ÌÌ‰")]
        public Nullable<System.DateTime> Hire_date { get; set; }
        public Nullable<int> Employee_national_services_status_id { get; set; }
        public Nullable<int> Experiences_years { get; set; }
        public Nullable<int> Employee_Job_id { get; set; }
        public Nullable<int> Employee_Rank_id { get; set; }
        public Nullable<int> Employee_Department_id { get; set; }
        public Nullable<int> Employee_fingerprint_id { get; set; }
        public Nullable<int> Employee_gender_id { get; set; }
    
        public virtual ICollection<alerts> alerts { get; set; }
        public virtual ICollection<Certificates> Certificates { get; set; }
        public virtual Countries Countries { get; set; }
        public virtual ICollection<Courses> Courses { get; set; }
        public virtual Departments Departments { get; set; }
        public virtual fingerprints fingerprints { get; set; }
        public virtual Genders Genders { get; set; }
        public virtual Qualifications Qualifications { get; set; }
        public virtual Jobs Jobs { get; set; }
        public virtual Marital_Status Marital_Status { get; set; }
        public virtual National_services_status National_services_status { get; set; }
        public virtual Qualifications Qualifications1 { get; set; }
        public virtual ranks ranks { get; set; }
        public virtual Religions Religions { get; set; }
        public virtual ICollection<Leave_permission> Leave_permission { get; set; }
        public virtual ICollection<Manifestations> Manifestations { get; set; }
        public virtual ICollection<Out_jobs> Out_jobs { get; set; }
        public virtual ICollection<Resigns> Resigns { get; set; }
        public virtual ICollection<sacks> sacks { get; set; }
        public virtual ICollection<stop_working> stop_working { get; set; }
        public virtual ICollection<Transfers> Transfers { get; set; }
        public virtual ICollection<Vacation_Balances> Vacation_Balances { get; set; }
        public virtual ICollection<Departments> Departments1 { get; set; }
        public virtual ICollection<Vacations> Vacations { get; set; }
    }
}
