//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace heshamhrms.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Leave_permission
    {
        public int leave_id { get; set; }
        [Display(Name = "«”„ «·„ÊŸ›")]
        

        public Nullable<int> leave_Employee_id { get; set; }
        [Display(Name = "› —… «·≈–‰")]
        

        public Nullable<int> leave_Duration { get; set; }
        [Display(Name = "«·”»»")]
        

        public string Leave_Reason { get; set; }
        [Display(Name = "«œŒ· »Ê«”ÿ…")]
        

        public Nullable<int> Edit_by { get; set; }
        [Display(Name = " «—ÌŒ «·«œŒ«·")]
        [DataType(DataType.Date)]

        public Nullable<System.DateTime> Date_time { get; set; }
        [Display(Name = "ÃÂ… «·Œ—ÊÃ")]
        

        public string leave_loc { get; set; }
    
        public virtual Employees Employees { get; set; }
        public virtual Users Users { get; set; }
    }
}
