//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace heshamhrms.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Locations
    {
        public Locations()
        {
            this.Departments = new HashSet<Departments>();
        }
    
        public int Location_id { get; set; }
        [Display(Name = "«”„ «·„ﬂ«‰")]
        public string Location_name { get; set; }
        [Display(Name = "«”„ «·„œÌ‰…")]
        public string city { get; set; }
        [Display(Name = "«·⁄‰Ê«‰")]
        public string address { get; set; }
        [Display(Name = "—ﬁ„ «·Â« ›")]
        public string Phone_no { get; set; }
    
        public virtual ICollection<Departments> Departments { get; set; }
    }
}
