//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace heshamhrms.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class hrmsEntities : DbContext
    {
        public hrmsEntities()
            : base("name=hrmsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<alerts> alerts { get; set; }
        public virtual DbSet<Authorities> Authorities { get; set; }
        public virtual DbSet<Certificates> Certificates { get; set; }
        public virtual DbSet<Countries> Countries { get; set; }
        public virtual DbSet<Courses> Courses { get; set; }
        public virtual DbSet<Courses_name> Courses_name { get; set; }
        public virtual DbSet<Departments> Departments { get; set; }
        public virtual DbSet<Employees> Employees { get; set; }
        public virtual DbSet<fingerprints> fingerprints { get; set; }
        public virtual DbSet<Genders> Genders { get; set; }
        public virtual DbSet<Hr_table_index> Hr_table_index { get; set; }
        public virtual DbSet<Jobs> Jobs { get; set; }
        public virtual DbSet<Leave_permission> Leave_permission { get; set; }
        public virtual DbSet<Locations> Locations { get; set; }
        public virtual DbSet<Manifestations> Manifestations { get; set; }
        public virtual DbSet<Marital_Status> Marital_Status { get; set; }
        public virtual DbSet<national_services> national_services { get; set; }
        public virtual DbSet<National_services_status> National_services_status { get; set; }
        public virtual DbSet<Out_jobs> Out_jobs { get; set; }
        public virtual DbSet<Qualifications> Qualifications { get; set; }
        public virtual DbSet<ranks> ranks { get; set; }
        public virtual DbSet<Religions> Religions { get; set; }
        public virtual DbSet<Resigns> Resigns { get; set; }
        public virtual DbSet<sacks> sacks { get; set; }
        public virtual DbSet<stop_working> stop_working { get; set; }
        public virtual DbSet<trainings> trainings { get; set; }
        public virtual DbSet<Transfers> Transfers { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<Vacation_Balances> Vacation_Balances { get; set; }
        public virtual DbSet<Vacations_type> Vacations_type { get; set; }
        public virtual DbSet<Vacations> Vacations { get; set; }
    }
}
