//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace heshamhrms.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Resigns
    {
        public int Resign_id { get; set; }
        public Nullable<int> Resign_Employee_id { get; set; }
        [Display(Name = " «—ÌŒ «·«” ﬁ«·…")]
        [DataType(DataType.Date)]

        public Nullable<System.DateTime> Resign_date { get; set; }
        [Display(Name = "«·”»»")]
        

        public string Resign_Reason { get; set; }
        public Nullable<int> Edit_by { get; set; }
        [Display(Name = " «—ÌŒ «·«œŒ«·")]
        [DataType(DataType.Date)]

        public Nullable<System.DateTime> Date_time { get; set; }
    
        public virtual Employees Employees { get; set; }
        public virtual Users Users { get; set; }
    }
}
