//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace heshamhrms.Models
{
    using System;
    using System.Collections.Generic;
  using System.ComponentModel.DataAnnotations;
    
    public partial class trainings
    {
        public int training_id { get; set; }
        [Display(Name = "«”„ «·„ œ—»")]
        
        public string training_name { get; set; }
        [Display(Name = " «—ÌŒ «·„Ì·«œ")]
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> Date_of_birth { get; set; }
        public Nullable<int> Country_id { get; set; }
        [Display(Name = "«·—ﬁ„ «·Êÿ‰Ì")]
        
        public Nullable<int> National_no { get; set; }
        [Display(Name = "—ﬁ„ «·Â« ›")]
        
        public string Phone_no { get; set; }
        public Nullable<int> training_Religion_id { get; set; }
        public Nullable<int> training_Marital_Status_id { get; set; }
        [Display(Name = "«·⁄‰Ê«‰")]
        
        public string Address { get; set; }
        public Nullable<int> training_Qualification_id { get; set; }
        [Display(Name = "«·Ã«„⁄…")]

        public string training_Qualification_university { get; set; }
        [Display(Name = " «—ÌŒ «·‘Â«œ…")]
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> training_Qualification_date { get; set; }
        [Display(Name = "»œ«Ì… «· œ—Ì»")]
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> Start_date { get; set; }
        [Display(Name = "‰Â«Ì… «· œ—Ì»")]
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> end_date { get; set; }
        public Nullable<int> Department_id { get; set; }
        public Nullable<int> fingerprint_id { get; set; }
    
        public virtual Countries Countries { get; set; }
        public virtual Departments Departments { get; set; }
        public virtual Marital_Status Marital_Status { get; set; }
        public virtual Qualifications Qualifications { get; set; }
        public virtual Religions Religions { get; set; }
    }
}
