//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace heshamhrms.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Transfers
    {
        public int Transfer_id { get; set; }
        [Display(Name = "«”„ «·„ÊŸ›")]
        

        public Nullable<int> Transfer_employee_id { get; set; }
        [Display(Name = "„‰")]
        

        public Nullable<int> Transfer_from_department_id { get; set; }
        [Display(Name = "«·Ì")]
        

        public Nullable<int> Transfer_to_department_id { get; set; }
        [Display(Name = "«œŒ· »Ê«”ÿ…")]
        

        public Nullable<int> Edit_by { get; set; }
        [Display(Name = " «—ÌŒ «·‰ﬁ·Ì…")]
        [DataType(DataType.Date)]

        public Nullable<System.DateTime> Date_time { get; set; }
    
        public virtual Departments Departments { get; set; }
        public virtual Departments Departments1 { get; set; }
        public virtual Employees Employees { get; set; }
        public virtual Users Users { get; set; }
    }
}
