//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace heshamhrms.Models
{
    using System;
    using System.Collections.Generic;
   using System.ComponentModel.DataAnnotations;
    
    public partial class Users
    {
        public Users()
        {
            this.alerts = new HashSet<alerts>();
            this.Certificates = new HashSet<Certificates>();
            this.Courses = new HashSet<Courses>();
            this.Leave_permission = new HashSet<Leave_permission>();
            this.Manifestations = new HashSet<Manifestations>();
            this.Out_jobs = new HashSet<Out_jobs>();
            this.Resigns = new HashSet<Resigns>();
            this.sacks = new HashSet<sacks>();
            this.stop_working = new HashSet<stop_working>();
            this.Transfers = new HashSet<Transfers>();
            this.Vacations = new HashSet<Vacations>();
        }
    
        public int User_id { get; set; }
        [Display(Name="«”„ «·„” Œœ„")]
        public string User_name { get; set; }
        [Display(Name = "ﬂ·„… «·„—Ê—")]
        public string password { get; set; }
        [Display(Name = "«·«”„ »«·ﬂ«„·")]
        public string fullname { get; set; }
        public string loginerr { get; set; }
        [Display(Name = "«·’·«ÕÌ…")]
        
        public Nullable<int> User_auth_id { get; set; }
    
        public virtual ICollection<alerts> alerts { get; set; }
        public virtual Authorities Authorities { get; set; }
        public virtual ICollection<Certificates> Certificates { get; set; }
        public virtual ICollection<Courses> Courses { get; set; }
        public virtual ICollection<Leave_permission> Leave_permission { get; set; }
        public virtual ICollection<Manifestations> Manifestations { get; set; }
        public virtual ICollection<Out_jobs> Out_jobs { get; set; }
        public virtual ICollection<Resigns> Resigns { get; set; }
        public virtual ICollection<sacks> sacks { get; set; }
        public virtual ICollection<stop_working> stop_working { get; set; }
        public virtual ICollection<Transfers> Transfers { get; set; }
        public virtual ICollection<Vacations> Vacations { get; set; }
    }
}
