//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace heshamhrms.Models
{
    using System;
    using System.Collections.Generic;
   using System.ComponentModel.DataAnnotations;
    
    public partial class Vacations_type
    {
        public Vacations_type()
        {
            this.Vacation_Balances = new HashSet<Vacation_Balances>();
            this.Vacations = new HashSet<Vacations>();
        }
    
        public int Vacation_type_id { get; set; }
	[Display(Name = "‰Ê⁄ «·«Ã«“…")]
        public string Vacation_name { get; set; }
    
        public virtual ICollection<Vacation_Balances> Vacation_Balances { get; set; }
        public virtual ICollection<Vacations> Vacations { get; set; }
    }
}
