//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace heshamhrms.Models
{
    using System;
    using System.Collections.Generic;
	using System.ComponentModel.DataAnnotations;
    
    public partial class Vacations
    {
        public int Vacation_id { get; set; }
        public Nullable<int> Vacation_employee_name { get; set; }
        public Nullable<int> Vacation_vt_id { get; set; }
        public Nullable<int> Vacation_depatrments_id { get; set; }
         [Display(Name = "«·„œ…")]
        public Nullable<int> Vacation_duration { get; set; }
         [Display(Name = "«·»œ«Ì…")]
         [DataType(DataType.Date)]
         public Nullable<System.DateTime> Vacation_start_date { get; set; }
         [Display(Name = "«·‰Â«Ì…")]
         [DataType(DataType.Date)]
         public Nullable<System.DateTime> Vacation_end_date { get; set; }
         [Display(Name = "«·”»»")]
         public string Vacation_Reason { get; set; }
         [Display(Name = "«œŒ· »Ê«”ÿ…")]
         public Nullable<int> Edit_by { get; set; }
         [Display(Name = " «—ÌŒ «·«œŒ«·")]
         [DataType(DataType.Date)]
        public Nullable<System.DateTime> Date_time { get; set; }
    
        public virtual Departments Departments { get; set; }
        public virtual Employees Employees { get; set; }
        public virtual Users Users { get; set; }
        public virtual Vacations_type Vacations_type { get; set; }
    }
}
